### ISSUE TITLE
Code formatting with rustfmt / cargo fmt

### ISSUE THREAD

**Issue by Johan-Mi** [d3r1n/brainsuck#1]
Please consider formatting your code with rustfmt, which can be done by running `cargo fmt`. This way, you'll get a consistent style and it will be easier for other people to contribute to the project. If you don't like the default configuration there's a list of options here: <https://rust-lang.github.io/rustfmt/>.

**Comment by d3r1n** [comment]
Thanks for the recommendation! I will format the code and add `.editorconfig` for others want to play around with source code.
